bash: add venv()

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -40,6 +40,30 @@ alias grep='grep --color=auto'
 alias fgrep='fgrep --color=auto'
 alias egrep='egrep --color=auto'
 
+# ----- functions -------------------------------
+
+# venv
+if type python3 >/dev/null; then
+	venv () {
+		if [ -n "${VIRTUAL_ENV}" ]; then
+			deactivate
+			return 0
+		fi
+
+		local VENV="./.venv"
+		local VENV_ACTIVATE="${VENV}/bin/activate"
+		if [ ! -d "${VENV}" ]; then
+			read -p 'Hit enter to create venv, or CTRL-C to cancel: '
+			python3 -m venv "${VENV}"
+		fi
+		if [ ! -e "${VENV_ACTIVATE}" ]; then
+			echo "${VENV_ACTIVATE} not found" >&2
+			return 1
+		fi
+		source ${VENV_ACTIVATE}
+	}
+fi
+
 # ----- source ----------------------------------
 
 # aliases
