change indent style to 4 spaces

diff --git a/dot/bashrc_remote b/dot/bashrc_remote
--- a/dot/bashrc_remote
+++ b/dot/bashrc_remote
@@ -1,27 +1,27 @@
 if type python3 &>/dev/null; then
-	venv () {
-		if [ -n "${VIRTUAL_ENV}" ]; then
-			deactivate
-			return 0
-		fi
+    venv () {
+        if [ -n "${VIRTUAL_ENV}" ]; then
+            deactivate
+            return 0
+        fi
 
-		local VENV=${1:-"./.venv"}
-		local VENV_ACTIVATE="${VENV}/bin/activate"
-		if [ ! -d "${VENV}" ]; then
-			read -p 'Hit enter to create venv, or CTRL-C to cancel ...'
-			python3 -m venv "${VENV}"
-			source "${VENV_ACTIVATE}"
-			python -m pip install --upgrade pip
-			return 0
-		fi
-		if [ ! -e "${VENV_ACTIVATE}" ]; then
-			echo "${VENV_ACTIVATE} not found" >&2
-			return 1
-		fi
-		source "${VENV_ACTIVATE}"
-	}
+        local VENV=${1:-"./.venv"}
+        local VENV_ACTIVATE="${VENV}/bin/activate"
+        if [ ! -d "${VENV}" ]; then
+            read -p 'Hit enter to create venv, or CTRL-C to cancel ...'
+            python3 -m venv "${VENV}"
+            source "${VENV_ACTIVATE}"
+            python -m pip install --upgrade pip
+            return 0
+        fi
+        if [ ! -e "${VENV_ACTIVATE}" ]; then
+            echo "${VENV_ACTIVATE} not found" >&2
+            return 1
+        fi
+        source "${VENV_ACTIVATE}"
+    }
 fi
 
 if [ -f "$HOME/.bashrc_local" ]; then
-	source "$HOME/.bashrc_local"
+    source "$HOME/.bashrc_local"
 fi
